language: php

addons:
  apt:
    packages:
      - php-apcu

php:
  - '7.3'
  - '7.4'
  - '8.0'

services:
  - redis

before_install:
  - echo "extension=apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/apcu.ini
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/apcu.ini

install:
  - composer install

script:
  - make analyze
  - make coverage

after_success:
  - travis_retry php vendor/bin/php-coveralls