language: php
php:
  - '7.2'

install:
  - sudo apt-get install redis php-apcu --assume-yes
  - sudo systemctl start redis
  - composer install

script:
  - make coverage

after_success:
  - travis_retry php vendor/bin/php-coveralls