language: php

addons:
  apt:
    packages:
      - php-apcu
      - sqlite3
php:
  - '7.3'
  - '7.4'
  - '8.0'

services:
  - redis

install:
  - composer install

script:
  - make analyze
  - make coverage

after_success:
  - travis_retry php vendor/bin/php-coveralls