language: php
php:
  - '7.2'

before_script:
  - sudo apt-get install php-apcu --assume-yes
  - sudo apt-get install redis --assume-yes
  - sudo systemctl start redis

install:
  - composer install

script:
  - make coverage

after_success:
  - travis_retry php vendor/bin/php-coveralls